// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XainportWeb.Data;

namespace XainportWeb.Migrations
{
    [DbContext(typeof(XainportWebContext))]
    [Migration("20200525181157_CreateAttestationSchema")]
    partial class CreateAttestationSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("XainportWeb.Models.Covid19AttestationModel", b =>
                {
                    b.Property<string>("XainportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Covid19Data")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("XainportId");

                    b.ToTable("Covid19AttestationModel");
                });
#pragma warning restore 612, 618
        }
    }
}
